column START_DATE_TRUNC new_value _START_DATE_TRUNC
column START_DATE new_value _START_DATE
column END_DATE   new_value _END_DATE
SET TERMOUT OFF
SELECT TO_CHAR(trunc(SYSDATE) - &_DATE_FILTER ,'DD/MM/YYYY HH24:MI:SS') AS START_DATE_TRUNC, 
       TO_CHAR(SYSDATE - &_DATE_FILTER ,'DD/MM/YYYY HH24:MI:SS') AS START_DATE, 
       TO_CHAR(SYSDATE ,'DD/MM/YYYY HH24:MI:SS') AS END_DATE 
FROM DUAL;
SET termout ON