set sqlprompt "@|blue _USER|@@@|green _CONNECT_IDENTIFIER|@@|blue > |@"
SELECT INSTANCE_NAME, STATUS, HOST_NAME, DATABASE_ROLE, OPEN_MODE, TO_CHAR(STARTUP_TIME,'YYYY-MM-DD HH24:MI:SS') AS STARTUP_TIME
FROM V$INSTANCE, V$DATABASE;
