SET FEEDBACK ON;
SET VERIFY OFF;
SET TIMING ON;

PROMP Coletando estatisticas para: ONWER = &1 TABLE_NAME = &2
BEGIN 
DBMS_STATS.GATHER_TABLE_STATS(
 OWNNAME=> upper('&1'),
 TABNAME=> upper('&2'),
 ESTIMATE_PERCENT=> DBMS_STATS.AUTO_SAMPLE_SIZE,
 method_opt => 'FOR ALL COLUMNS SIZE AUTO',
 CASCADE=>TRUE, 
 NO_INVALIDATE=>FALSE,
 DEGREE=>4
 );
END;
/

SET TIMING OFF;