set sqlformat
set long 99999
SET LINES 400
COL TASK_ID                             HEADING 'Task|ID'  FORMAT 999999
COL INMEMORY_SIZE                       HEADING 'In-Memory|Size (MB)'  FORMAT 999,999,999
COL ESTIMATED_DB_TIME_LOW               HEADING 'Low|Estimated|DB Time'  FORMAT 999999
COL ESTIMATED_DB_TIME_HIGH              HEADING 'High|Estimated|DB Time'  FORMAT 999999
COL ESTIMATED_DB_TIME_ANALYTICS_LOW     HEADING 'Low|Estimated|DB Time Analytics'  FORMAT 999999
COL ESTIMATED_DB_TIME_ANALYTICS_HIGH    HEADING 'High|Estimated|DB Time Analytics'  FORMAT 999999
COL RECOMMENDED_OBJ_LIST                HEADING 'Recommended | Object| List'  FORMAT A100
SELECT TASK_ID,
       INMEMORY_SIZE/1024/1024 INMEMORY_SIZE,
       ESTIMATED_DB_TIME_LOW,
       ESTIMATED_DB_TIME_HIGH,
       ESTIMATED_DB_TIME_ANALYTICS_LOW,
       ESTIMATED_DB_TIME_ANALYTICS_HIGH,
       RECOMMENDED_OBJ_LIST
FROM DBA_INMEMORY_ADVISOR_RECOMMENDATION
WHERE TASK_ID = 4;