COL JOINGROUP_OWNER   HEADING 'JoinGroup|Owner' FORMAT A15
COL JOINGROUP_NAME    HEADING 'JoinGroup|Name' FORMAT A30
COL TABLE_NAME        HEADING 'Table|Name' FORMAT a30
COL COLUMN_NAME       HEADING 'Column|Name' FORMAT a20
COL AUTO_CREATED      HEADING 'Auto|Created' FORMAT A8
COL CREATION_DATE     HEADING 'Creation|Date'  FORMAT A10
COL FLAGS             HEADING 'Flags' FORMAT 999
COL NUM_SYMBOLS       HEADING 'Number|Symbols'  FORMAT 999,999,999
COL GD_SIZE           HEADING 'GD|Size'  FORMAT 999,999,999
COL GD_ADDRESS        HEADING 'GD|Address' FORMAT A20
SELECT JOINGROUP_OWNER,
       JOINGROUP_NAME, 
       TABLE_NAME, 
       COLUMN_NAME, 
       AUTO_CREATED,
       CREATION_DATE,
       FLAGS,
       NUM_SYMBOLS,
       GD_SIZE,
       GD_ADDRESS
FROM   DBA_JOINGROUPS;