SET VERIFY OFF
WITH PLANOS AS (
  SELECT OBJECT_NAME AS INDEX_NAME, COUNT(DISTINCT(SQL_ID)) AS QT_SQL 
    FROM (
    SELECT OBJECT_NAME, SQL_ID
      FROM GV$SQL_PLAN 
     WHERE OPERATION='INDEX'
   UNION ALL
    SELECT OBJECT_NAME, SQL_ID
      FROM DBA_HIST_SQL_PLAN
     WHERE OPERATION='INDEX'
      )
GROUP BY OBJECT_NAME
)
   SELECT i.index_name
     FROM DBA_INDEXES I 
LEFT JOIN PLANOS P ON I.INDEX_NAME = P.INDEX_NAME
    WHERE 1=1
	  AND TABLE_NAME = '&1'
      AND P.QT_SQL IS NULL
/