SET LINESIZE 300
COL NAME FORMAT A30
COL SIGNATURE FORMAT 999999999999999999999
COL CREATED FORMAT A20
COL FORCE FORMAT A10
COL SQL_TEXT FORMAT A50
SELECT NAME, 
       SIGNATURE, 
       TO_CHAR(CREATED,'DD/MM/YYYY HH24:MI:SS') AS CREATED, 
       STATUS, 
       FORCE_MATCHING AS FORCE,
       SUBSTR(SQL_TEXT,1,50) as SQL_TEXT
FROM DBA_SQL_PATCHES
ORDER BY CREATED DESC;