SET LIN 1000
SET PAGESIZE 10000
SELECT * FROM table
 (DBMS_XPLAN.DISPLAY_CURSOR
   ( SQL_ID          => '&1', 
     CURSOR_CHILD_NO => &2, 
     FORMAT          => 'ALL ALLSTATS LAST +OUTLINE +NOTE +PEEKED_BINDS +PROJECTION +ALIAS +COST +BYTES +PARALLEL +PARTITION +REMOTE +ADAPTIVE'
    )
 );
