SET LINESIZE 300
SET PAGESIZE 500
COL SID FORMAT 99999
COL INST_ID FORMAT 99
COL STATUS FORMAT A10
COL MINUTES FORMAT 9,999
COL START_TIME FORMAT A20
COL SUSPEND_TIME FORMAT A20
COL MSG FORMAT A30
COL SQL_TEXT FORMAT A50
SELECT 
SESSION_ID SID,
INSTANCE_ID INST_ID,
STATUS,
ROUND(TIMEOUT/60) MINUTES,
START_TIME,
SUSPEND_TIME,
ERROR_NUMBER || '-'|| ERROR_MSG AS MSG,
SQL_TEXT
FROM DBA_RESUMABLE
WHERE SUSPEND_TIME IS NOT NULL
ORDER BY 2,1;