SET LINESIZE 300
SET PAGESIZE 500
COL SID FORMAT 99999
COL INST_ID FORMAT 99
COL STATUS FORMAT A10
COL MINUTES FORMAT 9,999
COL START_TIME FORMAT A20
COL SUSPEND_TIME FORMAT A20
COL MSG FORMAT A100
SELECT 
R.SESSION_ID SID,
R.INSTANCE_ID INST_ID,
S.SQL_ID,
R.STATUS,
ROUND(R.TIMEOUT/60) MINUTES,
R.START_TIME,
R.SUSPEND_TIME,
R.ERROR_MSG AS MSG
FROM DBA_RESUMABLE R
LEFT JOIN GV$SESSION S ON (R.SESSION_ID = S.SID AND R.INSTANCE_ID = S.INST_ID)
WHERE R.SUSPEND_TIME IS NOT NULL
ORDER BY 2,1;