SET VERIFY OFF
SET LINESIZE 400
SET PAGESIZE 500
COL SIGNATURE  FORMAT 9999999999999999999999
COL SQL_HANDLE FORMAT A20
COL PLAN_NAME  FORMAT A30
COL ORIGIN     FORMAT A15 TRUNC
COL CREATED    FORMAT A20
COL MODIFIED   FORMAT A20
COL ENABLED    FORMAT A8
COL ACCEPTED   FORMAT A7
COL ADAPTIVE   FORMAT A8
COL PLAN_HASH_VALUE FORMAT A15
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD/MM/YYYY HH24:MI:SS';
SELECT SIGNATURE, 
       SQL_HANDLE, 
       PLAN_NAME, 
       ORIGIN, 
       CREATED,
       LAST_MODIFIED as MODIFIED, 
       ENABLED, 
       ACCEPTED,
       ADAPTIVE 
     ,(select replace(plan_table_output,'Plan hash value: ','')
         from table(dbms_xplan.display_sql_plan_baseline('' || SQL_HANDLE || '','' || PLAN_NAME || ''))
        where plan_table_output like '%Plan hash value%'
          and rownum = 1
       ) as PLAN_HASH_VALUE
FROM DBA_SQL_PLAN_BASELINES
WHERE 1=1
ORDER BY CREATED DESC;
