set feedback off
SET SQLFORMAT
SET PAGES 50
SET LINES 400
COL JOB_NAME FORMAT A40
COL START_TIME FORMAT A20
COL STATUS FORMAT A15
COL STATE FORMAT A15
COL SQL_ID FORMAT A20
COL COMMENTS FORMAT A70

PROMP Jobs Pendentes:

SELECT JOB_NAME, 
       STATE, 
	   TO_CHAR(START_DATE,'DD/MM/YYYY HH24:MI:SS') AS START_DATE,
       SUBSTR(COMMENTS,1,70) AS COMMENTS
FROM DBA_SCHEDULER_JOBS 
WHERE JOB_NAME LIKE 'STA%';

PROMP
PROMP Jobs Finalizados:

SELECT JOB_NAME, 
       TO_CHAR(LOG_DATE,'DD/MM/YYYY HH24:MI:SS') AS LOG_DATE,
	   STATUS
FROM DBA_SCHEDULER_JOB_LOG 
WHERE JOB_NAME LIKE 'STA%' 
AND LOG_DATE >= SYSTIMESTAMP-2
ORDER BY LOG_ID DESC;

PROMP